steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/gcp-sample:$COMMIT_SHA', '.' ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gcp-sample:$COMMIT_SHA']
  # Create secret.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        cat << EOF >> app-secret.yaml
        PROJECT_ID: $PROJECT_ID
        CLOUD_TASKS_QUEUE_NAME: $$CLOUD_TASKS_QUEUE_NAME
        URL: $$URL
        LOCATION: $$LOCATION
        EOF
    secretEnv: ['CLOUD_TASKS_QUEUE_NAME', 'URL', 'LOCATION']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gcp-sample-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/gcp-sample:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--env-vars-file'
      - './app-secret.yaml'
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_NUMBER/secrets/CLOUD_TASKS_QUEUE_NAME/versions/latest
    env: 'CLOUD_TASKS_QUEUE_NAME'
  - versionName: projects/$PROJECT_NUMBER/secrets/URL/versions/latest
    env: 'URL'
  - versionName: projects/$PROJECT_NUMBER/secrets/LOCATION/versions/latest
    env: 'LOCATION'